### ISSUE TITLE
roadmap (dec 2024)

### ISSUE THREAD

**Issue by ismael-mendoza** [LSSTDESC/BPD#48]
## Current

- [x] #32
- [x] #55
- [x] #47 
- [x] #46 
- [x] #49
- [x] #51
- [x] add fisher predictions for comparsion to exp1
- [ ] ensure that prior on centroid is on deviation from detection, not on true centroid directly (Axel's comment)
- [x] #57
- [ ] #9 
- [ ] #18 

## Next

- [ ] demonstrate galaxy parameter inference with bulge+disk models
